# Generated by Django 4.0.5 on 2022-06-26 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='activity_type',
            field=models.TextField(blank=True, null=True, verbose_name='Основной вид деятельности по ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='average_percent_provided_coveralls',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Средний % обеспеченности работников СИЗ'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='average_percent_provided_disinfectants',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Средний % обеспечения работников смывающими средствами'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='count_of_workers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество работников, которые должны проходить обучение по охране труда и проверку знаний требований охраны труда в аккредитованных образовательных организациях'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='count_security_workers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Наличие уполномоченных (доверенных) лиц по охране труда (чел.)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_risk_valuation_done',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет'), ('PARTIALLY', 'Частично')], max_length=50, null=True, verbose_name='Проведена оценка профессиональных рисков в области охраны труда'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Полное наименование организации (для ИП - ФИО)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_safety_specialist',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО и должность специалиста по охране труда или ответственного за охрану труда'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='normative_act',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие локального нормативного акта, регламентирующего систему управления охраной труда'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='number_of_died_workers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших на производстве, чел'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='number_of_group_accidents',
            field=models.IntegerField(blank=True, null=True, verbose_name='Групповые несчастные случаи'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='number_of_hard_injury',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество человек, получивших тяжелые травмы'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='number_of_light_injury',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество человек, получивших легкие травмы'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='number_of_micro_injury',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество человек, получивших микротравмы'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail руководителя официальный'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='opf',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование ОПФ юрлица'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='percent_of_workers_with_medical_brief',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='% работников, прошедших обязательные предварительные и периодические медицинские осмотры'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='report_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата внесения отчета СОУТ'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='report_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер отчета во ФГИС СОУТ'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='risk_valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения последней оценки профессиональных рисков'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое наименование организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='specialist_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail специалиста по охране труда официальный'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='valuated_workplace_percent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='% рабочих мест, охваченых СОУТ'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='workers_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Среднесписочная численность работников на дату проведения мониторинга — Ч (с указанием мужчин - М, женщин - Ж)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='workers_number_with_free_coveralls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность работников, получающих бесплатно спецодежду, спецобувь и другие средства индивидуальной защиты (СИЗ)– всего:'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='workers_number_with_free_disinfectants',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность работников, получающих бесплатно смывающие и обезвреживающие средства – всего:'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='workers_number_with_medical_brief',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество работников, подлежащих обязательным предварительным и периодическим медицинским осмотрам'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='workers_on_danger_positions_percent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='% рабочих на опасных местах'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='workplace_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего рабочих мест в организации'),
        ),
    ]
