# Generated by Django 4.0.5 on 2022-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_organisation_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='activity_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Основной вид деятельности по ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='change_agreement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Изменения в колдоговор'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='collective_agreement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наличие коллективного договора'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='fact_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='gold_sign',
            field=models.CharField(blank=True, choices=[('CONFIRMED', 'Подтвержен'), ('MISSING', 'Отсутсвует'), ('UNDER_CONSIDERATION', 'На рассмотрении')], default='Отсутсвует', max_length=50, null=True, verbose_name='Золотой знак'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='leader_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО руководителя и должность'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное наименование организации (для ИП - ФИО)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_safety_specialist',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО и должность специалиста по охране труда или ответственного за охрану труда'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='opf',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование ОПФ юрлица'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткое наименование организации'),
        ),
    ]
