# Generated by Django 4.0.5 on 2022-06-26 15:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_organisation_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='gold_sign',
            field=models.CharField(choices=[('CONFIRMED', 'Подтвержен'), ('MISSING', 'Отсутсвует'), ('UNDER_CONSIDERATION', 'На рассмотрении')], default='Отсутствует', max_length=50, verbose_name='Золотой знак'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(default=app.models.instances_count, max_length=250, verbose_name='Краткое наименование организации'),
        ),
    ]
